enum GameActions {
    playerImmortal,
    renderPhaserOn,
    renderPhaserOff,
    hitboxesOn,
    hitboxesOff,
    addEnemy,
    removeEnemy,
    addExplosionCenter,
    removeExplosionCenter,
    addParticle,
    removeParticle,
    phaserOnScreen,
    phaserOffScreen,
    numberOfEnemies,
    level,
    addToScore,
    setLives,
    addLife,
    removeLife,
    setPlayer,
    setBullet,
    setPlayerFormationPhase,
    increaseScore,
    pauseOn,
    pauseOff,
    playerMortal
}

export default GameActions;